Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -34,4 +34,4 @@ jobs:
         run: echo ::set-output name=test::$(cat test.txt)
         
       - name: Test output
-        run: if docker logs TFLint foo; then echo error|| exit 2; else echo All ok; fi
+        run: if "docker logs TFLint" foo; then echo error|| exit 2; else echo All ok; fi
